#!/bin/sh
### BEGIN INIT INFO
# Provides:          monitorPB
# Required-Start:    rsyslog 
# Required-Stop: 
# Default-Start: 2 3 4 5
# Default-Stop:  0 1 6 
# x-Stop-Before: 
# x-Stop-After: 
# Short-Description: launches monitorPB.py to moniotor power switch
# Description:       launches monitorPB.py to moniotor power switch
### END INIT INFO
#
# start: start the power button monitor
# stop: do nothing
# restart: do nothing
#

case "$1" in
  start)
	/usr/bin/logger "monitorPB:starting power switch monitor"
	/usr/bin/python /etc/init.d/monitorPB.py 2>&1 | /usr/bin/logger &
	/usr/bin/logger "monitorPB:python exit status $?"
	;;
  stop)
	echo -n "Stopping nothing..."
	;;
  restart)
	echo -n "Restarting nothing..."
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

