#!/bin/sh

### BEGIN INIT INFO
# Provides:          monitorPS
# Required-Start:    rsyslog 
# Required-Stop: 
# Default-Start: 2 3 4 5
# Default-Stop:  0 1 6 
# x-Stop-Before: 
# x-Stop-After: 
# Short-Description: launches monitorPS.py to moniotor battery level
# Description:       launches monitorPS.py to moniotor battery level
### END INIT INFO
#
# start: start the battery level monitor.  If low battery is detected
# monitorPS.py will start the shutdown 
#

case "$1" in
  start)
	/usr/bin/logger "monitorPS:starting power supply monitor"
	/usr/bin/python /etc/init.d/monitorPS.py 2>&1 | /usr/bin/logger &
	/usr/bin/logger "monitorPS:python exit status $?"
	;;
  stop)
	echo -n "Stopping nothing..."
	;;
  restart|reload)
	echo -n "restarting"
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

